src/config/swagger.ts, src/input/index.ts, src/input/input-type.model.ts, src/input/input-unit-of-measure.model.ts, src/input/input.controller.ts, src/input/input.interface.ts, src/input/input.model.ts, src/input/input.repository.ts, src/input/input.route.ts, src/input/input.schema.ts, src/input/input.service.ts, src/server.ts, src/supplier/index.ts
- Added input.routes.ts to handle input-related routes
- Created input.repository.ts to handle database operations for inputs
- Updated server.ts to include inputRoutes
- Added Input model, InputType model, InputUnitOfMeasure model
- Added interfaces for FindAllDTO, CreateInputDTO, and UpdateInputDTO
=> feat: add input funtionality

src/config/swagger.ts, src/machinery/machinery-brand.model.ts, src/machinery/machinery-maintenance.model.ts, src/machinery/machinery-model.model.ts, src/machinery/machinery-status.model.ts, src/machinery/machinery-type.model.ts, src/machinery/machinery.controller.ts, src/machinery/machinery.interfase.ts, src/machinery/machinery.model.ts, src/machinery/machinery.repository.ts, src/machinery/machinery.route.ts, src/machinery/machinery.schema.ts, src/machinery/machinery.service.ts, src/server.ts
This commit adds the necessary files and routes for handling machinery-related functionality. It includes the creation of the `machinery.interface.ts`, `machinery.schema.ts`, `machinery-type.model.ts`, `machinery-brand.model.ts`, `machinery-model.model.ts`, `machinery-status.model.ts`, `machinery-maintenance.model.ts`, and `machinery.repository.ts` files. These files define the interfaces, schemas, models, and repositories for machinery data. Additionally, the `machinery.route.ts` file is created to handle the routes for machinery operations. This commit lays the foundation for managing machinery in the application.
=> feat: Add machinery-related files and routes

src/machinery/machinery-location.model.ts, src/machinery/machinery-maintenance.model.ts, src/machinery/machinery.controller.ts, src/machinery/machinery.interfase.ts, src/machinery/machinery.model.ts, src/machinery/machinery.repository.ts, src/machinery/machinery.route.ts, src/machinery/machinery.schema.ts, src/machinery/machinery.service.ts
This commit adds the `machinery-location.model.ts` file, which defines the model for tracking the location history of machinery. It also includes the necessary associations with the `Machinery` and `Employee` models. Additionally, the `machinery-location.repository.ts` file is created to handle the database operations related to machinery location. This enhancement allows for tracking the assignment and modification dates of machinery, providing valuable information for maintenance and management purposes.
=> feat: Add machinery location model and related files

src/quotation/quotation.interfase.ts, src/quotation/quotation.model.ts, src/quotation/quotation.repository.ts, src/quotation/quotation.route.ts, src/quotation/quotation.schema.ts, src/quotation/quotation.service.ts
- consecutive
- builder
- builderAddress
- projectName
- itemSummary To the Quotation model
=> added the fields

src/quotation/quotation-item-detail.model.ts, src/quotation/quotation-item.model.ts, src/quotation/quotation.interfase.ts, src/quotation/quotation.repository.ts, src/quotation/quotation.route.ts, src/quotation/quotation.schema.ts, src/quotation/quotation.service.ts
refactor quotation models and schemas to use string types for quantity, unitPrice, total, and totalCost
=> refactor quotation 

src/repositories/employee/employee.repository.ts, src/work-tracking/work-tracking.controller.ts, src/work-tracking/work-tracking.route.ts, src/work-tracking/work-tracking.service.ts
add generateReport method to WorkTrackingService and corresponding route and controller logic
=> feat: add generateReport

src/quotation/quotation.repository.ts, src/quotation/quotation.service.ts
update findQuotationAdditionalCostById method to use findOne for better querying
=> fix: findQuotationAdditionalCostById

src/quotation/quotation.service.ts
update utility calculation in quotation summary to multiply by subtotal
=> fix: update utility calculation 

src/quotation/quotation.interfase.ts, src/quotation/quotation.model.ts, src/quotation/quotation.route.ts, src/quotation/quotation.schema.ts
add client, executionTime, policy, and technicalCondition fields to quotation models and schemas
=> feat: modified quotation model

src/order/order-item.model.ts, src/order/order.controller.ts, src/order/order.interface.ts, src/order/order.repository.ts, src/order/order.route.ts, src/order/order.service.ts
add documentUrl field to order item and implement file upload handling in create and update methods
=> feat: upload files

src/order/order-item.model.ts, src/order/order.interface.ts, src/order/order.repository.ts, src/order/order.route.ts, src/order/order.schema.ts, src/order/order.service.ts
replace phone field with orderRequest in OrderItem model and up date related interfaces, schemas, and services
=> feat: replace phone by orderModel

src/order/order.repository.ts
update OrderRepository to replace phone field with orderRequest in CostCenterProject attributes
=> replace phone field with orderRequest

src/order/order.repository.ts
update OrderRepository to change order sorting to DESC and adjust CostCenterProject attributes
=> OrderRepository to change order sorting to DESC

src/order/order.service.ts
fix item filter in OrderService to correctly reference request  parameters
=> feat: fix item filter in OrderService

src/features/cost-center/cost-center-project.model.ts, src/features/cost-center/cost-center.controller.ts, src/features/cost-center/cost-center.interfase.ts, src/features/cost-center/cost-center.repository.ts, src/features/cost-center/cost-center.route.ts, src/features/cost-center/cost-center.schema.ts, src/features/cost-center/cost-center.service.ts, src/features/cost-center/project-item.model.ts
add ProjectItem model and CRUD operations for project items in CostCenter
=> feat: project items

src/features/quotation/quotation.interfase.ts, src/features/quotation/quotation.route.ts, src/features/quotation/quotation.schema.ts, src/features/quotation/quotation.service.ts
update quotation interfaces and schemas to include optional idQuotation and idQuotationItem fields
=> feat: add filter to quotation item detail

src/features/quotation/quotation.service.ts
correct idQuotation reference in QuotationService to use Quotati onItem
=> fix: correct filter quotation item detail

src/features/quotation/quotation.repository.ts, src/features/quotation/quotation.service.ts
enhance quotation item details response with additional attributes and improve pagination handling
=> fix: fixed response for summary of quotation

src/config/swagger.ts, src/features/expenditure/expenditure-item.model.ts, src/features/expenditure/expenditure.controller.ts, src/features/expenditure/expenditure.interface.ts, src/features/expenditure/expenditure.model.ts, src/features/expenditure/expenditure.repository.ts, src/features/expenditure/expenditure.route.ts, src/features/expenditure/expenditure.schema.ts, src/features/expenditure/expenditure.service.ts, src/features/expenditure/expendityre-type.model.ts, src/features/expenditure/index.ts, src/server.ts, src/utils/general.interfase.ts
add expenditure feature with models, routes, and pagination support
=> feat: expenditure feature

src/features/expenditure/expenditure.controller.ts, src/features/expenditure/expenditure.repository.ts, src/features/expenditure/expenditure.route.ts, src/features/expenditure/expenditure.service.ts
add endpoint to retrieve all expenditure types with corresponding service and repository methods
=> feat: expenditure types

src/features/expenditure/expenditure.service.ts
enhance expenditure service with pagination and total values calculation
=> feat: total values

src/features/expenditure/expenditure.interface.ts, src/features/expenditure/expenditure.model.ts, src/features/expenditure/expenditure.route.ts, src/features/expenditure/expenditure.schema.ts
change refundRequestDate type from Date to string in expenditure models and schemas
=> feat: change refundRequestDate type 

src/features/expenditure/expenditure.interface.ts, src/features/expenditure/expenditure.model.ts, src/features/expenditure/expenditure.route.ts, src/features/expenditure/expenditure.schema.ts, src/features/expenditure/expenditure.service.ts
add month and year filters, and fromDate and toDate fields to expenditure models and schemas
=> feat: filter and new fields on model Expenditure

src/features/expenditure/expenditure.model.ts
add createdAt and updatedAt fields to Expenditure model for better tracking
=> feat: add createdAt and updatedAt fields to Expenditure model

src/features/order/order-item-detail.model.ts, src/features/revenue-center/revenue-center.model.ts, src/features/revenue-center/revenue-center.repository.ts, src/features/revenue-center/revenue-center.schema.ts, src/features/revenue-center/revenue-center.service.ts
RevenueCenterRepository and update service methods to utilize it
=> feat: implement findAllInput method
